# Generated by Django 4.0.6 on 2022-07-30 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.board'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.TextField(max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='kanban.category'),
        ),
    ]
